spring:
  config:
    import: optional:file:project.env[.properties]
  application:
    name: budget

application:
  password: ${APPLICATION_PASSWORD}
  sheet-id: ${SHEET_ID}
  google-secret: ${GOOGLE_SECRET}